const safePayrollErrors: ReadonlyArray<readonly [string, string]> = [
  ["PAYROLL_PERMISSION_DENIED", "You do not have permission to perform this payroll action."],
  ["PAYROLL_SETTINGS_INVALID", "Review the payroll settings and try again."],
  ["PAYROLL_SCHEDULE_NOT_FOUND", "The selected payroll schedule could not be found."],
  ["PAYROLL_SCHEDULE_INVALID", "Review the payroll schedule details and try again."],
  ["PAYROLL_SCHEDULE_IN_USE", "This payroll schedule is assigned to current or future employees."],
  ["PAYROLL_PERIOD_NOT_FOUND", "The selected payroll period could not be found."],
  ["PAYROLL_PERIOD_TRANSITION_INVALID", "This payroll period cannot move to the selected status."],
  ["PAYROLL_PERIOD_VERSION_CONFLICT", "The payroll period changed. Reload and try again."],
  ["PAYROLL_PERIOD_REOPEN_REASON_REQUIRED", "A reason is required to reopen a locked payroll period."],
  ["PAYROLL_COMPENSATION_NOT_FOUND", "The selected compensation record could not be found."],
  ["PAYROLL_COMPENSATION_INVALID", "Review the compensation details and try again."],
  ["PAYROLL_COMPENSATION_OVERLAP", "A compensation record already applies during this date range."],
  ["PAYROLL_COMPENSATION_IMMUTABLE", "Approved compensation records cannot be edited."],
  ["PAYROLL_BACKDATED_REASON_REQUIRED", "A reason and confirmation are required for a backdated compensation change."],
  ["PAYROLL_ASSIGNMENT_NOT_FOUND", "The selected payroll schedule assignment could not be found."],
  ["PAYROLL_ASSIGNMENT_INVALID", "Review the payroll schedule assignment and try again."],
  ["PAYROLL_ASSIGNMENT_OVERLAP", "A payroll schedule assignment already applies during this date range."],
  ["PAYROLL_ASSIGNMENT_MID_PERIOD", "This schedule change begins inside a payroll period and requires an approved override."],
  ["PAYROLL_REQUEST_STATE_INVALID", "This request is no longer in a state that allows the selected action."],
  ["PAYROLL_REQUEST_VERSION_CONFLICT", "This request changed. Reload and try again."],
  ["PAYROLL_GENERATION_ALREADY_RUNNING", "Payroll period generation is already running."],
  ["PAYROLL_GENERATION_FAILED", "Payroll periods could not be generated."],
  ["PAYROLL_BASIS_INVALID", "Review the payroll basis rule and try again."],
  ["PAYROLL_BASIS_NOT_FOUND", "The selected payroll basis rule could not be found."],
  ["PAYROLL_BASIS_REQUIRED", "Approve a payroll basis rule before starting calculations."],
  ["PAYROLL_BASIS_STATUS_INVALID", "This payroll basis rule cannot perform the selected action."],
  ["PAYROLL_BASIS_FUTURE_CONFLICT", "Another approved payroll basis rule conflicts with this effective date."],
  ["PAYROLL_CALCULATION_ALREADY_RUNNING", "Another calculation run is already active for this payroll period."],
  ["PAYROLL_CALCULATION_MODE_INVALID", "Choose a valid payroll calculation mode."],
  ["PAYROLL_CALCULATION_RUN_NOT_FOUND", "The payroll calculation run could not be found."],
  ["PAYROLL_CALCULATION_IMMUTABLE", "Completed payroll calculation records cannot be changed."],
  ["PAYROLL_PERIOD_CALCULATION_INVALID", "This payroll period is not open for calculation."],
  ["PAYROLL_PERIOD_NOT_READY", "Resolve blocking exceptions and stale payroll entries before review."],
  ["PAYROLL_EMPLOYEE_NOT_FOUND", "The selected employee could not be included in this payroll period."],
  ["PAYROLL_EXCEPTION_NOT_FOUND", "The selected payroll exception could not be found or is already resolved."],
  ["PAYROLL_EXCLUSION_NOT_FOUND", "The selected payroll exclusion could not be found or was already reversed."],
  ["PAYROLL_BLOCKING_EXCEPTION_REQUIRES_RECALCULATION", "Correct the source data and recalculate this employee before resolving the blocker."],
  ["PAYROLL_PREMIUM_SCOPE_INVALID", "Choose a valid premium-rule scope."],
  ["PAYROLL_PREMIUM_RULE_INVALID", "Review the premium-rule settings and try again."],
  ["PAYROLL_PREMIUM_RULE_NOT_FOUND", "The selected premium rule could not be found."],
  ["PAYROLL_PREMIUM_RULE_IMMUTABLE", "Approved premium rules cannot be edited."],
  ["PAYROLL_PREMIUM_RULE_STATUS_INVALID", "This premium rule cannot perform the selected action."],
  ["PAYROLL_PREMIUM_RULE_CONFLICT", "Another approved premium rule conflicts with this scope and date range."],
  ["PAYROLL_PREMIUM_RULE_REQUIRED", "Approve a company-default premium rule before calculating premiums."],
  ["PAYROLL_PREMIUM_ROUNDING_INVALID", "Review the premium-time rounding settings."],
  ["PAYROLL_ATTENDANCE_DEDUCTION_RULE_INVALID", "Review the attendance deduction settings."],
  ["PAYROLL_PREMIUM_CALCULATION_FAILED", "Payroll premiums could not be calculated."],
  ["PAYROLL_PREMIUM_IMMUTABLE", "Completed premium calculation records cannot be changed."],
  ["PAYROLL_REASON_REQUIRED", "A reason is required for this payroll action."],
];

export function mapPayrollError(
  message: string,
  fallback = "The payroll request could not be completed. Please try again.",
) {
  return safePayrollErrors.find(([code]) => message.includes(code))?.[1] ?? fallback;
}
