"use client";
import { useActionState, useState } from "react";
import { createCompensationDraftAction, updateCompensationDraftAction } from "@/app/(dashboard)/employees/[id]/compensation/actions";
import type { CompensationType } from "@/features/payroll/constants";
import type { CompensationRecord, PayrollActionState } from "@/features/payroll/types";
const initial: PayrollActionState = {};
export function CompensationForm({ employeeId, currencyCode, companyDate, suggestedEffectiveDate, record }: { employeeId: string; currencyCode: string; companyDate: string; suggestedEffectiveDate: string | null; record?: CompensationRecord }) {
  const [type, setType] = useState<CompensationType>(record?.compensationType ?? "monthly");
  const [effectiveFrom, setEffectiveFrom] = useState(record?.effectiveFrom ?? suggestedEffectiveDate ?? companyDate);
  const action = record
    ? async (_: PayrollActionState, data: FormData) => updateCompensationDraftAction(employeeId, data)
    : async (_: PayrollActionState, data: FormData) => createCompensationDraftAction(employeeId, data);
  const [state, formAction, pending] = useActionState(action, initial);
  const backdated = effectiveFrom < companyDate;
  return <form className="card content-stack" action={formAction}>{record ? <><input type="hidden" name="recordId" value={record.id}/><input type="hidden" name="expectedVersion" value={record.version}/></> : null}<div className="section-heading"><div><h2>{record ? "Edit compensation draft" : "New compensation draft"}</h2><p>Approved records are immutable. Changes become active only after Super Admin approval.</p></div></div><div className="form-grid"><label>Compensation type<select className="field" name="compensationType" value={type} onChange={(event) => setType(event.target.value as CompensationType)}><option value="monthly">Monthly salary</option><option value="hourly">Hourly rate</option></select></label><label>Currency<input className="field" value={currencyCode} readOnly aria-readonly="true"/></label><label>Monthly salary<input className="field" type="number" step="0.01" min="0.01" name="monthlySalary" defaultValue={record?.monthlySalary ?? ""} disabled={type !== "monthly"} required={type === "monthly"}/></label><label>Hourly rate<input className="field" type="number" step="0.01" min="0.01" name="hourlyRate" defaultValue={record?.hourlyRate ?? ""} disabled={type !== "hourly"} required={type === "hourly"}/></label><label>Standard hours per day<input className="field" type="number" step="0.25" min="0.25" max="24" name="standardHoursPerDay" defaultValue={record?.standardHoursPerDay ?? 8} required/></label><label>Standard hours per week<input className="field" type="number" step="0.25" min="0.25" max="168" name="standardHoursPerWeek" defaultValue={record?.standardHoursPerWeek ?? 40} required/></label><label>Effective date<input className="field" type="date" name="effectiveFrom" value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} required/></label><label className="detail-span">Change reason<textarea className="field" name="changeReason" defaultValue={record?.changeReason ?? ""} required={backdated} maxLength={1000}/></label></div>{backdated ? <p className="form-error">This is a backdated change. A reason and explicit Super Admin confirmation will be required.</p> : null}{state.error ? <p className="form-error" role="alert">{state.error}</p> : null}{state.success ? <p className="form-success" role="status">{state.success}</p> : null}<div className="form-actions"><button className="btn primary" disabled={pending}>{pending ? "Saving…" : record ? "Save draft" : "Create draft"}</button></div></form>;
}
