"use client";
import { useActionState, useState } from "react";
import { createPayrollScheduleAction, updatePayrollScheduleAction } from "@/app/(dashboard)/payroll/schedules/actions";
import type { PayrollScheduleType } from "@/features/payroll/constants";
import type { PayrollActionState, PayrollScheduleDetail, PayrollScheduleInput } from "@/features/payroll/types";

const initial: PayrollActionState = {};
export function PayrollScheduleForm({ schedule, initialInput }: { schedule?: PayrollScheduleDetail; initialInput?: PayrollScheduleInput }) {
  const values = schedule ?? initialInput;
  const [type, setType] = useState(values?.scheduleType ?? "semi_monthly");
  const action = schedule
    ? async (_state: PayrollActionState, data: FormData) => updatePayrollScheduleAction(data)
    : async (_state: PayrollActionState, data: FormData) => createPayrollScheduleAction(data);
  const [state, formAction, pending] = useActionState(action, initial);
  return <form className="card content-stack" action={formAction}><div className="section-heading"><div><h2>{schedule ? "Edit payroll schedule" : "Create payroll schedule"}</h2><p>Currency and timezone are inherited from company payroll settings.</p></div></div>{schedule ? <><input type="hidden" name="scheduleId" value={schedule.id}/><input type="hidden" name="expectedVersion" value={schedule.version}/></> : null}<div className="form-grid"><label>Name<input className="field" name="name" defaultValue={values?.name ?? ""} required maxLength={120}/></label><label>Code<input className="field" name="code" defaultValue={values?.code ?? ""} required maxLength={16}/></label><label>Frequency<select className="field" name="scheduleType" value={type} onChange={(event) => setType(event.target.value as PayrollScheduleType)} disabled={Boolean(schedule)}><option value="weekly">Weekly</option><option value="biweekly">Biweekly</option><option value="semi_monthly">Semi-monthly</option><option value="monthly">Monthly</option></select>{schedule ? <input type="hidden" name="scheduleType" value={type}/> : null}</label><label>Currency<input className="field" value={schedule?.currencyCode ?? "PHP"} readOnly aria-readonly="true"/></label><label>Timezone<input className="field" value={schedule?.timezone ?? "Asia/Manila"} readOnly aria-readonly="true"/></label>{type === "weekly" || type === "biweekly" ? <label>Anchor date<input className="field" type="date" name="anchorDate" defaultValue={values?.anchorDate ?? ""} required/></label> : <input type="hidden" name="anchorDate" value=""/>}{type === "semi_monthly" ? <label>First period end day<input className="field" type="number" min="1" max="27" name="firstPeriodEndDay" defaultValue={values?.firstPeriodEndDay ?? 15} required/></label> : <input type="hidden" name="firstPeriodEndDay" value=""/>}<label>Cutoff offset days<input className="field" type="number" min="-31" max="31" name="cutoffOffsetDays" defaultValue={values?.cutoffOffsetDays ?? 0} required/></label><label>Payment offset days<input className="field" type="number" min="-31" max="62" name="paymentOffsetDays" defaultValue={values?.paymentOffsetDays ?? 5} required/></label></div>{state.error ? <p className="form-error" role="alert">{state.error}</p> : null}{state.success ? <p className="form-success" role="status">{state.success}</p> : null}<div className="form-actions">{!schedule ? <button className="btn" type="submit" formAction="/payroll/schedules/new" formMethod="get" name="preview" value="1" disabled={pending}>Preview dates</button> : null}<button className="btn primary" disabled={pending}>{pending ? "Saving…" : schedule ? "Save changes" : "Create schedule"}</button></div></form>;
}
