import Link from "next/link";
import { formatPayrollDate, payrollRequestStatusLabel, premiumRuleScopeLabel } from "@/features/payroll/presentation";
import type { PremiumRuleList } from "@/features/payroll/types";

export function PremiumRuleList({ data }: { data: PremiumRuleList }) {
  const today = new Date().toISOString().slice(0, 10);
  const activeDefault = data.rules.find((rule) => rule.scopeType === "company_default" && rule.status === "approved" && rule.effectiveFrom <= today && (!rule.effectiveTo || rule.effectiveTo >= today));
  return <div className="content-stack">
    {!activeDefault ? <section className="card payroll-setup-warning"><span className="badge warning">Setup required</span><div><h2>No active company-default premium rule</h2><p>Clone or create a draft, verify its source and multipliers, then obtain Super Admin approval before calculating premiums.</p></div></section> : <section className="card payroll-run-summary"><div><span className="muted">Active premium rule</span><h2>{activeDefault.name}</h2><p>{premiumRuleScopeLabel(activeDefault.scopeType)} · effective {formatPayrollDate(activeDefault.effectiveFrom)}</p></div><span className="badge success">Approved</span></section>}
    <section className="content-stack"><div className="section-heading"><div><h2>Reference presets</h2><p>Reference templates do not affect payroll until cloned, reviewed, submitted, and approved.</p></div><Link className="btn primary" href="/payroll/settings/premium-rules/new">Create custom rule</Link></div><div className="payroll-basis-grid">{data.presets.map((preset) => <article className="card content-stack" key={preset.code}><div><span className="badge info">Reference only</span><h3>{preset.name}</h3><p>{preset.sourceAgency}</p></div><p className="muted">{preset.sourceReference}</p><Link className="btn" href={`/payroll/settings/premium-rules/new?preset=${encodeURIComponent(preset.code)}`}>Review and create draft</Link></article>)}</div></section>
    <section className="content-stack"><div className="section-heading"><div><h2>Premium-rule history</h2><p>Draft, pending, approved, rejected, future, and superseded versions.</p></div><span className="badge info">{data.rules.length}</span></div>{data.rules.length ? <div className="payroll-basis-grid">{data.rules.map((rule) => <article className="card content-stack" key={rule.id}><div className="card-header-row"><div><h3>{rule.name}</h3><p className="muted">{rule.scopeLabel} · Version {rule.version}</p></div><span className={`badge ${rule.status === "approved" ? "success" : rule.status === "rejected" ? "danger" : rule.status === "pending_approval" ? "warning" : "info"}`}>{payrollRequestStatusLabel(rule.status)}</span></div><dl className="detail-list"><div><dt>Scope</dt><dd>{premiumRuleScopeLabel(rule.scopeType)}</dd></div><div><dt>Effective</dt><dd>{formatPayrollDate(rule.effectiveFrom)} – {formatPayrollDate(rule.effectiveTo)}</dd></div><div><dt>Source</dt><dd>{rule.sourceAgency}</dd></div><div><dt>Day types</dt><dd>{rule.dayRules.length}</dd></div></dl><Link className="btn" href={`/payroll/settings/premium-rules/${rule.id}`}>View rule</Link></article>)}</div> : <div className="card empty">No premium rules have been created.</div>}</section>
  </div>;
}
