"use client";

import { useActionState } from "react";
import { approvePremiumRuleSetAction, clonePremiumRuleVersionAction, rejectPremiumRuleSetAction, submitPremiumRuleSetAction } from "@/app/(dashboard)/payroll/premiums/actions";
import { formatPayrollDate, formatPayrollDateTime, payrollRequestStatusLabel, premiumDayTypeLabel, premiumTimeRoundingModeLabel } from "@/features/payroll/presentation";
import type { PayrollActionState, PremiumCoveragePreview, PremiumRuleSet } from "@/features/payroll/types";

const initial: PayrollActionState = {};
type Action = (data: FormData) => Promise<PayrollActionState>;
function Feedback({ state }: { state: PayrollActionState }) { return <>{state.error ? <p className="form-error">{state.error}</p> : null}{state.success ? <p className="form-success">{state.success}</p> : null}</>; }
function useRuleAction(action: Action) { return useActionState(async (_: PayrollActionState, data: FormData) => action(data), initial); }

export function PremiumRuleDetail({ rule, coverage, canApprove }: { rule: PremiumRuleSet; coverage: PremiumCoveragePreview; canApprove: boolean }) {
  const [submitState, submitAction, submitting] = useRuleAction(submitPremiumRuleSetAction);
  const [approveState, approveAction, approving] = useRuleAction(approvePremiumRuleSetAction);
  const [rejectState, rejectAction, rejecting] = useRuleAction(rejectPremiumRuleSetAction);
  const [cloneState, cloneAction, cloning] = useRuleAction(clonePremiumRuleVersionAction);
  return <div className="content-stack">
    <section className="card content-stack"><div className="card-header-row"><div><h2>{rule.name}</h2><p>{rule.scopeLabel} · Version {rule.version}</p></div><span className="badge info">{payrollRequestStatusLabel(rule.status)}</span></div><dl className="detail-list"><div><dt>Effective</dt><dd>{formatPayrollDate(rule.effectiveFrom)} – {formatPayrollDate(rule.effectiveTo)}</dd></div><div><dt>Submitted</dt><dd>{formatPayrollDateTime(rule.submittedAt)}</dd></div><div><dt>Approved</dt><dd>{formatPayrollDateTime(rule.approvedAt)}</dd></div><div><dt>Legal source</dt><dd><a href={rule.sourceUrl} target="_blank" rel="noreferrer">{rule.sourceAgency} · {rule.sourceReference}</a></dd></div></dl>{rule.changeReason ? <p><strong>Change reason:</strong> {rule.changeReason}</p> : null}{rule.rejectionReason ? <p className="form-error"><strong>Rejection reason:</strong> {rule.rejectionReason}</p> : null}</section>
    <section className="card content-stack"><div className="section-heading"><div><h2>Coverage preview</h2><p>Preview only; no payroll values are recalculated.</p></div></div><div className="metric-grid"><div><span>Affected employees</span><strong>{coverage.affectedEmployeeCount}</strong></div><div><span>Open periods</span><strong>{coverage.affectedOpenPeriodCount}</strong></div><div><span>Potential stale entries</span><strong>{coverage.staleEntryCount}</strong></div><div><span>Conflicts</span><strong>{coverage.conflictingRuleIds.length}</strong></div></div>{coverage.missingDayTypes.length ? <p className="form-error">Missing: {coverage.missingDayTypes.map(premiumDayTypeLabel).join(", ")}</p> : null}</section>
    <section className="content-stack"><div className="section-heading"><div><h2>Day-type multipliers</h2><p>Approved versions are immutable.</p></div></div><div className="premium-rule-grid">{rule.dayRules.map((day) => <article className="card content-stack" key={day.id}><h3>{premiumDayTypeLabel(day.dayType)}</h3><dl className="detail-list"><div><dt>Day multiplier</dt><dd>{day.regularTimeMultiplier}</dd></div><div><dt>OT multiplier</dt><dd>{day.overtimeMultiplier}</dd></div><div><dt>Night differential</dt><dd>{day.nightDifferentialPercentage}</dd></div><div><dt>Night window</dt><dd>{day.nightWindowStart}–{day.nightWindowEnd}</dd></div><div><dt>OT rounding</dt><dd>{premiumTimeRoundingModeLabel(day.overtimeRoundingMode)}</dd></div><div><dt>Night rounding</dt><dd>{premiumTimeRoundingModeLabel(day.nightRoundingMode)}</dd></div></dl></article>)}</div></section>
    {rule.status === "draft" ? <form className="card content-stack" action={submitAction}><input type="hidden" name="ruleId" value={rule.id}/><input type="hidden" name="expectedVersion" value={rule.version}/><button className="btn primary" disabled={submitting}>{submitting ? "Submitting…" : "Submit for approval"}</button><Feedback state={submitState}/></form> : null}
    {rule.status === "pending_approval" && canApprove ? <section className="card payroll-basis-actions"><form action={approveAction}><input type="hidden" name="ruleId" value={rule.id}/><input type="hidden" name="expectedVersion" value={rule.version}/><button className="btn primary" disabled={approving}>{approving ? "Approving…" : "Approve"}</button><Feedback state={approveState}/></form><form className="content-stack" action={rejectAction}><input type="hidden" name="ruleId" value={rule.id}/><input type="hidden" name="expectedVersion" value={rule.version}/><label>Rejection reason<textarea className="field" name="reason" required maxLength={1000}/></label><button className="btn danger-outline" disabled={rejecting}>{rejecting ? "Rejecting…" : "Reject"}</button><Feedback state={rejectState}/></form></section> : null}
    {["approved", "rejected", "superseded"].includes(rule.status) ? <form className="card form-grid" action={cloneAction}><input type="hidden" name="id" value={rule.id}/><label>New effective date<input className="field" type="date" name="effective_from" required/></label><label>New end date<input className="field" type="date" name="effective_to"/></label><label className="detail-span">Change reason<textarea className="field" name="change_reason" required maxLength={1000}/></label><button className="btn" disabled={cloning}>{cloning ? "Creating…" : "Clone as new version"}</button><Feedback state={cloneState}/></form> : null}
  </div>;
}
