"use client";
import { useActionState, useState } from "react";
import { createScheduleAssignmentDraftAction, updateScheduleAssignmentDraftAction } from "@/app/(dashboard)/employees/[id]/compensation/actions";
import type { PayrollActionState, PayrollScheduleAssignment, PayrollScheduleSummary } from "@/features/payroll/types";
const initial: PayrollActionState = {};
export function ScheduleAssignmentForm({ employeeId, schedules, suggestedEffectiveDate, assignment }: { employeeId: string; schedules: PayrollScheduleSummary[]; suggestedEffectiveDate: string | null; assignment?: PayrollScheduleAssignment }) {
  const [override, setOverride] = useState(assignment?.overrideMidPeriod ?? false);
  const action = assignment
    ? async (_: PayrollActionState, data: FormData) => updateScheduleAssignmentDraftAction(employeeId, data)
    : async (_: PayrollActionState, data: FormData) => createScheduleAssignmentDraftAction(employeeId, data);
  const [state, formAction, pending] = useActionState(action, initial);
  return <form className="card content-stack" action={formAction}>{assignment ? <><input type="hidden" name="assignmentId" value={assignment.id}/><input type="hidden" name="expectedVersion" value={assignment.version}/></> : null}<div className="section-heading"><div><h2>{assignment ? "Edit schedule assignment" : "New schedule assignment"}</h2><p>The suggested date is the next available payroll period start.</p></div></div><div className="form-grid"><label>Payroll schedule<select className="field" name="payrollScheduleId" defaultValue={assignment?.payrollScheduleId ?? ""} required><option value="" disabled>Choose a schedule</option>{schedules.filter((item) => item.isActive || item.id === assignment?.payrollScheduleId).map((schedule) => <option key={schedule.id} value={schedule.id}>{schedule.name} ({schedule.code})</option>)}</select></label><label>Effective date<input className="field" type="date" name="effectiveFrom" defaultValue={assignment?.effectiveFrom ?? suggestedEffectiveDate ?? ""} required/></label><label className="detail-span">Change reason<textarea className="field" name="changeReason" defaultValue={assignment?.changeReason ?? ""} maxLength={1000}/></label><label className="checkbox-row detail-span"><input type="checkbox" name="overrideMidPeriod" checked={override} onChange={(event) => setOverride(event.target.checked)}/>Request a mid-period override</label>{override ? <label className="detail-span">Override reason<textarea className="field" name="overrideReason" defaultValue={assignment?.overrideReason ?? ""} required maxLength={1000}/></label> : <input type="hidden" name="overrideReason" value=""/>}</div>{state.error ? <p className="form-error">{state.error}</p> : null}{state.success ? <p className="form-success">{state.success}</p> : null}<button className="btn primary" disabled={pending}>{pending ? "Saving…" : assignment ? "Save assignment draft" : "Create assignment draft"}</button></form>;
}
