"use client";

import { useActionState, useMemo, useState } from "react";
import type { ScheduleActionState, ScheduleEmployeeOption } from "@/features/schedules/types";

export function BulkAssignmentForm({ action, employees, schedules, companyDate }: { action: (state: ScheduleActionState, formData: FormData) => Promise<ScheduleActionState>; employees: ScheduleEmployeeOption[]; schedules: Array<{ id: string; code: string; name: string }>; companyDate: string }) {
  const [state, formAction, pending] = useActionState(action, {});
  const [query, setQuery] = useState("");
  const [departmentId, setDepartmentId] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const departments = useMemo(() => Array.from(new Map(employees.filter((item) => item.department).map((item) => [item.department!.id, item.department!])).values()), [employees]);
  const visible = useMemo(() => employees.filter((employee) => {
    const search = `${employee.first_name} ${employee.last_name} ${employee.employee_number}`.toLowerCase();
    return (!query || search.includes(query.toLowerCase())) && (!departmentId || employee.department_id === departmentId);
  }), [employees, query, departmentId]);
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  function selectVisible() { setSelected((current) => Array.from(new Set([...current, ...visible.map((item) => item.id)]))); }
  return <form action={formAction} className="card form-card schedule-form"><div className="form-grid"><label><span>Schedule</span><select className="field" name="schedule_template_id" required><option value="">Select schedule</option>{schedules.map((schedule) => <option key={schedule.id} value={schedule.id}>{schedule.code} · {schedule.name}</option>)}</select></label><label><span>Effective start</span><input className="field" type="date" name="effective_start_date" defaultValue={companyDate} required /></label><label><span>Effective end <span className="muted">(optional)</span></span><input className="field" type="date" name="effective_end_date" /></label><label className="full"><span>Assignment reason <span className="muted">(required when backdated)</span></span><textarea className="field" name="assignment_reason" maxLength={1000} rows={4} /></label></div><section><div className="section-heading-row"><h2>Select employees</h2><strong>{selected.length} selected</strong></div><div className="employee-selection-toolbar"><input className="field" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name or employee number" /><select className="field" value={departmentId} onChange={(event) => setDepartmentId(event.target.value)}><option value="">All departments</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select><button className="btn" type="button" onClick={selectVisible}>Select all visible</button><button className="btn" type="button" onClick={() => setSelected([])}>Clear selection</button></div><div className="employee-selection-list">{visible.map((employee) => <label className="employee-selection-row" key={employee.id}><input type="checkbox" name="employee_ids" value={employee.id} checked={selected.includes(employee.id)} onChange={() => toggle(employee.id)} /><span><strong>{employee.last_name}, {employee.first_name}</strong><br /><span className="muted">{employee.employee_number} · {employee.department?.name ?? "No department"}</span></span></label>)}</div></section>{state.error && <p className="form-error">{state.error}</p>}<div className="confirmation-note">This operation is all-or-nothing. Current assignments will end and future assignments on or after the selected start date will be superseded for every selected employee.</div><button className="btn primary" disabled={pending || selected.length === 0}>{pending ? "Assigning…" : `Assign ${selected.length} employee${selected.length === 1 ? "" : "s"}`}</button></form>;
}
