"use client";

import { useActionState } from "react";
import type { ScheduleActionState, ScheduleEmployeeOption } from "@/features/schedules/types";

export function IndividualAssignmentForm({ action, employees, schedules, defaultEmployeeId = "", companyDate }: { action: (state: ScheduleActionState, formData: FormData) => Promise<ScheduleActionState>; employees: ScheduleEmployeeOption[]; schedules: Array<{ id: string; code: string; name: string }>; defaultEmployeeId?: string; companyDate: string }) {
  const [state, formAction, pending] = useActionState(action, {});
  return <form action={formAction} className="card form-card schedule-form"><div className="form-grid"><label><span>Employee</span><select className="field" name="employee_ids" defaultValue={defaultEmployeeId} required><option value="">Select employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.last_name}, {employee.first_name} · {employee.employee_number}</option>)}</select></label><label><span>Schedule</span><select className="field" name="schedule_template_id" required><option value="">Select schedule</option>{schedules.map((schedule) => <option key={schedule.id} value={schedule.id}>{schedule.code} · {schedule.name}</option>)}</select></label><label><span>Effective start</span><input className="field" type="date" name="effective_start_date" defaultValue={companyDate} required /></label><label><span>Effective end <span className="muted">(optional)</span></span><input className="field" type="date" name="effective_end_date" /></label><label className="full"><span>Assignment reason <span className="muted">(required when backdated)</span></span><textarea className="field" name="assignment_reason" maxLength={1000} rows={4} /></label></div>{state.error && <p className="form-error">{state.error}</p>}<div className="confirmation-note">The preceding assignment will end the day before this start date. Future assignments on or after this date will be superseded.</div><button className="btn primary" disabled={pending}>{pending ? "Assigning…" : "Assign schedule"}</button></form>;
}
