import Link from "next/link";
import type { ResolvedEmployeeSchedule } from "@/features/schedules/types";
import { ScheduleSummary } from "./schedule-summary";

export function MyScheduleCard({ schedule }: { schedule: ResolvedEmployeeSchedule }) {
  if (schedule.state === "unassigned") return <section className="card schedule-template-card"><span className="badge warning">Unassigned schedule</span><h2>No work schedule is currently assigned.</h2><p className="muted">You may continue to clock in and out. Scheduled-hour calculations will remain unavailable until HR assigns a schedule.</p>{schedule.upcomingAssignment && <p><strong>Upcoming:</strong> {schedule.upcomingAssignment.template.name} effective {schedule.upcomingAssignment.effective_start_date}</p>}</section>;
  if (schedule.state === "unavailable" || !schedule.assignment || !schedule.version) return <section className="card schedule-template-card"><span className="badge danger">Schedule unavailable</span><h2>Schedule information is temporarily unavailable.</h2><p className="muted">Contact HR to review the schedule configuration.</p></section>;
  return <section className="card schedule-template-card"><div className="section-heading-row"><div><span className="muted">{schedule.template?.code}</span><h2>{schedule.template?.name}</h2></div><span className={`badge ${schedule.state === "rest_day" ? "info" : "success"}`}>{schedule.state === "rest_day" ? "Rest day" : "Scheduled workday"}</span></div><ScheduleSummary version={schedule.version} /><p className="muted">Assignment effective {schedule.assignment.effective_start_date}{schedule.assignment.effective_end_date ? ` through ${schedule.assignment.effective_end_date}` : " onward"}.</p>{schedule.upcomingAssignment && <div className="confirmation-note"><strong>Upcoming change:</strong> {schedule.upcomingAssignment.template.name} effective {schedule.upcomingAssignment.effective_start_date}</div>}<Link className="btn" href="/attendance">View attendance</Link></section>;
}
